package exptrunner.jmetal;

public enum Metrics {
	COMBINED_DIST_METRIC,
	AVOIDANCE_METRIC,
	TIME_PROP,
	TIME_TOTAL_ABSOLUTE,
	NUM_FAULTS,
	FIRST_FAULT_TIME,
	DETECTION_COMPLETION_TIME,
	OBSTACLE_AVOIDANCE_METRIC
};
